# Generated by Django 4.2 on 2023-11-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
