# Generated by Django 4.2 on 2023-11-03 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_collect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name='分享标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='分享内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='分享人')),
            ],
            options={
                'verbose_name_plural': '分享内容',
            },
        ),
        migrations.CreateModel(
            name='CommentSharing',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('comment_count', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.commentsharing')),
                ('sharing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.sharing')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
