# Generated by Django 4.2.7 on 2023-12-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_sharing_options_alter_sharing_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='friend_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='maiden_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
